version: '3.7'
services:
  my_postgres:
    image: postgres:16.3-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Supermarket
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data


